### ISSUE TITLE
hello, can you give me an example.

### ISSUE THREAD

**Issue by ChrisFernandez** [vicvega/hpfeeds-ruby#3]
I keep getting 
ERROR: "accessfail."
ERROR: "accessfail."

but I am putting the right info server and port.
for testing im just leaving your example as it is.. Im trying to sent data to my hpfeeds broker.
@hp.publish('message', '#{chan}')  <-- this is the only change I done, apart of the channel names and auth information.

**Comment by vicvega** [comment]
You got an `accessfail` if you try to publish on a channel that does not exist
